import { Metadata } from "next";
import localFont from "next/font/local";

import Navbar from './components/Navbar';
import Footer from './components/Footer';
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const interFontUrl = "https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href={interFontUrl} />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* Diğer meta etiketler ve stil bağlantıları */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-inter`}
        >

        <Navbar />
        <main>{children}</main>
        <Footer />

      </body>
    </html>
  );
}
